### ISSUE TITLE
Doesn't work at all for me

### ISSUE THREAD

**Issue by joshkaplan** [stuartcryan/rapid-browser-tabs-for-alfred#11]
I have followed the instruction to the letter, but I cannot get this script to work.

I have tried navigating to the workflow directory directly and running `load_list.rb` directly, and receive the following errors (I'm on ruby 2.3.0 freshly installed via `brew`):

With no parameters:

```
$ ruby load_list.rb
load_list.rb:17:in `<main>': undefined method `strip' for nil:NilClass (NoMethodError)
```

With one parameter "test":

```
ruby load_list.rb test
/Users/josh/Dropbox/Dev/Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A8961C80-CDCD-44D5-8342-9FC7F1519779/browser_tabs/applescript_utils.rb:37:in `block in osascript': AppleScript error: osascript: OpenScripting.framework - scripting addition "/Library/ScriptingAdditions/Numerics.osax" cannot be used with the current OS because it has no OSAXHandlers entry in its Info.plist. (BrowserTabs::AppleScriptUtils::AppleScriptError)
osascript: OpenScripting.framework - scripting addition "/Library/ScriptingAdditions/Satimage.osax" cannot be used with the current OS because it has no OSAXHandlers entry in its Info.plist.
osascript: OpenScripting.framework - scripting addition "/Library/ScriptingAdditions/XMLLib.osax" cannot be used with the current OS because it has no OSAXHandlers entry in its Info.plist.
osascript: OpenScripting.framework - scripting addition "/Users/josh/Library/ScriptingAdditions/YouHelper.osax" cannot be used with the current OS because it has no OSAXHandlers entry in its Info.plist.
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/open3.rb:205:in `popen_run'
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/open3.rb:95:in `popen3'
    from /Users/josh/Dropbox/Dev/Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A8961C80-CDCD-44D5-8342-9FC7F1519779/browser_tabs/applescript_utils.rb:32:in `osascript'
    from /Users/josh/Dropbox/Dev/Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A8961C80-CDCD-44D5-8342-9FC7F1519779/browser_tabs/applescript_utils.rb:18:in `run'
    from /Users/josh/Dropbox/Dev/Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A8961C80-CDCD-44D5-8342-9FC7F1519779/browser_tabs/commands/command.rb:49:in `run'
    from /Users/josh/Dropbox/Dev/Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A8961C80-CDCD-44D5-8342-9FC7F1519779/browser_tabs.rb:62:in `run_command'
    from /Users/josh/Dropbox/Dev/Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A8961C80-CDCD-44D5-8342-9FC7F1519779/browser_tabs.rb:31:in `tabs'
    from load_list.rb:18:in `<main>'
```

Not to familiar with Applescript or Ruby, so any help is much appreciated.

**Comment by joshkaplan** [comment]
Turns out this was due to some broken ScriptingExtensions that had gotten installed in one way or another. I cleared out the offending files form `/Library/ScriptingAdditions/` and `~/Library/ScriptingAdditions/` and that solved the issue.
